// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLpRsD5FQxAaGtdoCfynogNpKoAB1WUL0',
    appId: '1:251381610747:android:087b33aeeae9a0d393585e',
    messagingSenderId: '251381610747',
    projectId: 'ghamidiapp-s',
    databaseURL: 'https://ghamidiapp-s-default-rtdb.firebaseio.com',
    storageBucket: 'ghamidiapp-s.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8Q8eo8bfv1SmDEUxSM46Ggv8IdQADEXw',
    appId: '1:251381610747:ios:91d5bd6391668e9b93585e',
    messagingSenderId: '251381610747',
    projectId: 'ghamidiapp-s',
    databaseURL: 'https://ghamidiapp-s-default-rtdb.firebaseio.com',
    storageBucket: 'ghamidiapp-s.appspot.com',
    androidClientId: '251381610747-50ikhcuo704s07p52dgc804f4kvj0sfj.apps.googleusercontent.com',
    iosBundleId: 'com.ghamidi.part.two',
  );

}